### ISSUE TITLE
Support SvelteKit instead of Next

### ISSUE THREAD

**Issue by liamwh** [t3-oss/create-t3-app#1061]
### Is your feature request related to a problem? Please describe.

Support SvelteKit instead of Next

### Describe the solution you'd like to see

Support SvelteKi/Svelte instead of Next/React

### Describe alternate solutions

N/A

**Comment by t3dotgg** [comment]
Feel free to fork and make your own :) ct3a is very built into next at the moment. We've already seen similar projects with other frameworks like Nuxt and solid start

**Comment by asrvd** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> Support SvelteKit instead of Next
> 
> ### Describe the solution you'd like to see
> 
> Support SvelteKi/Svelte instead of Next/React
> 
> ### Describe alternate solutions
> 
> N/A
> 
> ### Additional information
> 
> _No response_

I have actually tried integrating t3 stack with sveltekit and tbh it aint worth it for now at least. Since authjs is not yet stable, moreover using trpc and authjs together in sveltekit breaks a lot of stuff too. Here's the app made using sveltekit with t3 stack and honestly I don't like it very much cus it's not at all easy to setup - https://github.com/asrvd/sveltekit-guestbook
