### ISSUE TITLE
feat: add two-way server <=> client binding to the demo app

### ISSUE THREAD

**Issue by jdevries3133** [t3-oss/create-t3-app#1079]
### Is your feature request related to a problem? Please describe.

This two-way binding pattern is very common. I am new to react-query, this project is actually what is bringing me into this ecosystem. As I'm trying to familiarize myself, this was one of the first thing I explored, and I think that the t3 boilerplate would be stronger if it included some kind of example like this.

### Describe the solution you'd like to see

I have a diff that you can see here which demonstrates exactly what I'm talking about: https://github.com/jdevries3133/t3_two_way_binding/pull/1

The mutation invalidates the query so that the page "live updates" when the button is clicked.

I do think it's strange that the boilerplate includes the "example" resource, complete with db schema and some backend operations, but it just doesn't quite expose it in the client!

### Describe alternate solutions

I think an ideal solution would actually have a bit of delay on the backend, and maybe even a random (say 30%) chance of an error to make a cool demo of the full feature-set that we're offering here, but these are bells and whistles that I don't necessarily need to see; just a thought.

I also think that we might just want to keep the demo app lean and get people to RTFM, and I'd accept that answer too!

**Comment by c-ehrlich** [comment]
Thanks for the issue and the sample diff. 

I agree that the `example` resource feels a bit weird currently depending on what is scaffolded. It's intended to exists as basic Prisma documentation (but is kind of worthless when an app is initialized with next-auth because that comes with its own schema). 

Reasons to do it:
- Gives the `example` resource more of a purpose
- I agree that it works great in terms of documentation/education
- It would very clearly be a demo of tRPC functionality - I suspect some people don't even realize what the "Hello from tRPC" text is doing, an interactive demo would be more clear about this

Reasons not to do it:
- More code in the starter template (we've been working hard to keep it as slim as possible, especially index.tsx). This is undesireable for two reasons:
    1. I suspect most people just rip out the example router and index.tsx after scaffolding
    2. The more code we include the less likely people are to read any of it, so adding more stuff actually decreases the educational value of the existing stuff.
- It's primarily about showing how tRPC works, but it will only exist in apps that include Prisma.
    - could just mutate an array in apps without Prisma, but that feels like it actively hurts the educational nature as our main deploy target is serverless where something like that doesn't work
- Creates even more variety in the index files (app with tRPC but without Prisma should still have "hello from tRPC", app with tRPC and Prisma should have the `example` demo and maybe(?) still the "hello from tRPC demo as well) - but I personally don't think this is a big deal

I'm not sure yet which set of arguments I find more convincing, would be nice to get some other opinions :)

One thing I do feel strongly about is that if we do it, I think it should be the smallest possible example, ie no delay / random error throwing etc.

**Comment by jdevries3133** [comment]
Good insights, I totally agree with the trade-offs you've laid out.

One thing I'd call into question is the haste with which people remove the default router and index files. If a user is new to the tech, they'll keep that stuff around to refer back to it, so the more db <=> frontend functionality we can pack into as few lines as possible the better. I do think that CRUD on a single resource is a very valid thing to have if it's a Prisma + tRPC situation. With next-auth we could make deletion a protected action. Having the resource be timestamps like the example model we already have seems ok to me. 

I agree that the random error / artificial loading times are a bit much lol
