### ISSUE TITLE
feat: Display Prettier errors in files

### ISSUE THREAD

**Issue by ArturHaidau** [t3-oss/create-t3-app#1381]
### Is your feature request related to a problem? Please describe.

When I create a new T3 project and make some changes to files, I am not able to see any prettier errors in my VS Code.

I would like to see something like this, when I've just created a new project.

https://user-images.githubusercontent.com/122266851/233999969-db493862-005f-4fd8-a0d9-8dc9b38f504b.mp4

As I see, current version of an initial T3 project doesn't show any prettier errors.

### Describe the solution you'd like to see

I suggest to use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier)

And make updates for the `eslintrc.cjs` file:
1.Add `"prettier"` to the list of plugins
2.Add `"prettier/prettier": "error"` to the `rules`

### Describe alternate solutions

Leave this choice to users

**Comment by c-ehrlich** [comment]
Prettier is not something the developer should be worrying about while writing code. Leave that for things that cause actual problems. Prettier errors are fixed on save, and if they're not because a developer's local setup isn't working properly then they will be flagged in CI.

That being said we intentionally ship a very unopinionated prettier config so you can add whatever you want to it.
