### ISSUE TITLE
feat: replace tRPC with server actions from NextJS13

### ISSUE THREAD

**Issue by Lucasvo1** [t3-oss/create-t3-app#1456]
### Is your feature request related to a problem? Please describe.

With server actions there is a more lightweight, zero configuration and type-safe way to handle data fetching.

### Describe the solution you'd like to see

Remove tRPC and put in some examples using server actions.

### Describe alternate solutions

No alternative solutions.

**Comment by c-ehrlich** [comment]
see https://github.com/t3-oss/create-t3-app/issues/1364

**Comment by sscotth** [comment]
TBF, I don't think server actions is referenced in #1364 only appDir. Either way, server actions are in alpha, not even beta. So see the [bleed responsibly axiom](https://create.t3.gg/en/introduction#bleed-responsibly) until it becomes stable.

**Comment by Lucasvo1** [comment]
> TBF, I don't think server actions are referenced in #1364 only appDir. Either way, server actions are in [alpha](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions), not even beta yet. So it will very likely have significant breaking changes, replaced with something else, or dropped altogether. See the [bleed responsibly axiom](https://create.t3.gg/en/introduction#bleed-responsibly) until it becomes stable.

Well, like you see with the appDir, it's better to start working on it now so that it's ready once it hits stable.

**Comment by anaibol** [comment]
I think Trpc integration on Nextjs is not only about data fetching but also about data state management on the frontend.

**Comment by Kamahl19** [comment]
@c-ehrlich Server actions are now stable, do you plan doing this?

**Comment by c-ehrlich** [comment]
> @c-ehrlich Server actions are now stable, do you plan doing this?

No.

We do "support" server actions, in the sense that it's a Next.js app and you can use them. But we have no plans to get rid of tRPC.

The Next.js team [recommends using a data access layer](https://nextjs.org/blog/security-nextjs-server-components-actions#choosing-your-data-handling-model) for anything but quick prototyping. tRPC is that data layer for us.

In fact I'd recommend it even for quick prototyping, because:
- you get better dx
- you get better type safety
- you get react query integration in client components
- it's no extra work for you because Create T3 App takes care of all of the initial setup

**Comment by Kamahl19** [comment]
The recommendation you linked only talks about the separation of concerns and not mixing data access with UI components. It says nothing about bringing 3rd party tools such as tRPC or Query into the stack. Doing this is also possible using "native/idiomatic" techniques which Server Actions are now, in Nextjs v14. Doing more with less should always be a preferred way.

**Comment by tomer-dev** [comment]
Adding to what @Kamahl19 said, I understand the part in the article on "Data access layer" as a recommendation to move the data access part into a package where you can check input and auth, and on top of all you use DTOs.

Looking at Theo's related videos I couldn't find a response as to why tRPC is needed when we have server actions.

Theo said at the end of the "React+Servers Confusion" video that 
an import async call on a client side for a server action on a different file, (eventually becomes a FETCH call)..
"it's almost like an RPC".

I really love the work you do, I allow myself to jump up this Q again from that place, I'd like to hear your opinion on this.

**Comment by tomer-dev** [comment]
Adding to what @Kamahl19 said, I understand the part in the article on "Data access layer" as a recommendation for new projects to move the data access part into a package where you can check input and auth, and on top of all you use DTOs.

After watching the "React+Servers=Confusion" video, I wonder what's the role of tRPC if we have the DTOs defined and we import server actions. Especially when the server actions can be imported on the client side.

I really love the work you do. I allow myself to raise this Q again as we learn and adapt to these new changes.

**Comment by tomer-dev** [comment]
https://www.reddit.com/r/nextjs/comments/16foyg1/why_use_trpc_procedures_as_server_actions_in/

**Comment by tomer-dev** [comment]
[Reddit discussion on keeping tRPC despite server actions in](https://www.reddit.com/r/nextjs/comments/16foyg1/why_use_trpc_procedures_as_server_actions_in/)

After some research, let me know if tRPC integration with React Query and Next.js may be a reason for keeping tRPC even though with server actions we have the ability to RPC. From [tRPC docs](
https://trpc.io/docs/client/nextjs):
> Our Next.js integration is built on top of our [React Query Integration](https://trpc.io/docs/) with some Next.js specific APIs, to handle both client and server side rendering.

Currently, making that server action call from the client will trigger a fetch call, extended by Next.js.

**Comment by tomer-dev** [comment]
[Reddit discussion on keeping tRPC despite server actions in](https://www.reddit.com/r/nextjs/comments/16foyg1/why_use_trpc_procedures_as_server_actions_in/)

After some research, let me know if tRPC integration with React Query and Next.js may be a reason for keeping tRPC even though with server actions we can RPC. From [tRPC docs](https://trpc.io/docs/client/nextjs):

Our Next.js integration is built on top of our [React Query Integration](https://trpc.io/docs/) with some Next.js-specific APIs, to handle both client and server-side rendering.

Currently, making that server action call from the client will trigger a fetch call, extended by Next.js.
Perhaps it is not yet compelling to shift from the benefits tRPC brings to server actions.

**Comment by tomer-dev** [comment]
[Reddit discussion on keeping tRPC despite server actions in](https://www.reddit.com/r/nextjs/comments/16foyg1/why_use_trpc_procedures_as_server_actions_in/)

After some research, let me know if tRPC integration with React Query and Next.js may be a reason for keeping tRPC even though with server actions we can RPC. From [tRPC docs](https://trpc.io/docs/client/nextjs):

> Our Next.js integration is built on top of our [React Query Integration](https://trpc.io/docs/) with some Next.js-specific APIs, to handle both client and server-side rendering.

Currently, making that server action call from the client will trigger a fetch call, extended by Next.js.
Perhaps the benefits from server actions are still not more compelling than those offered by tRPC?

**Comment by markomitranic** [comment]
@tomer-dev It is perfectly normal to use both react query and server actions, I use that in my projects:
```ts
  const { error } = useQuery({
    queryKey: ["posts"],
    queryFn: () => myServerAction("post-id"),
  });
```

**Comment by issamwahbi** [comment]
Hey,

@markomitranic , you are using a server action to fetch data with react-query. Nextjs are not recommanding this in their officiel documentation even if it works. From what I test,  it fetch data with a POST request ..weird from web standards point of view !! it seems the recommanded approach from NEXTJS to fetch data is to use a server component...but not sur if that can cover all the cases. 

In addition, I don't think server actions can yet replace tRPC functionalities. Server actions from client are a kind of RPCs. So you need from a good design point of view  to handle data validation, authentication, authorization, error management ... before executing the server action logic. The best way in my opinion to do that is using a kind of middleware pattern. Some libraries out their like next-safe-action are trying to solve it. 

I will even argue that at the moment tRPC is a better design decision than server actions. it gives more flexibility. For exemple if you need to reuse your api routes in a react native application. 

in my opinion what will be the "ideal" solution is to be able to create tRPC routes as we do today and have a way to generate dynamically a server actions from it. with type safety and dynamic piping of the route middleware...

**Comment by tomer-dev** [comment]
It feels like React Server Actions are stepping on Next's toes, and it is
confusing.

It is ok to have different patterns, but they should be declared as such.

React would go out of its way so much to imitate "better" a feature done by
Next? they work so closely.

**Comment by markomitranic** [comment]
@issamwahbi I understand what you are saying. I just want to clarify 2 things.

Try to differentiate between the domain logic we have to write (which is literally the same for any transport method) and the transport method itself. Be it HTTP, trpc, ws, server actions, or even server components - you still have to do auth, sanitization and validation and api minimization. Yes the shape of doing it may vary but you still have to do it every single time.

Now, focusing on the differences between transport methods - it is perfectly fine to use POST, a good example of that is graphql. The main reason not to use POST is the (im)possibility of CDN level caching, which has plagued graphql for the past decade. And, it is literally the same for both trpc and actions, both are uncacheable in a similar way. That is the real reason why HTTP+GET is being always recommended - it thrives on caching. With that said, it is clear that this doesn't really make any difference between trpc and actions.

As for tanstack-query, that is a misconception - you can in fact use it with literally anything. You can use it with local async functions as well, for example. T3 Trpc uses it as well. So saying that they can't or shouldn't be used with server actions is kinda silly. But not so silly if you think about it - a large majority of the user base of NextJS is new to the basic backend concepts, and expect the NextJS team to set boundaries and best practices, which is percicely why they chose to say `bad idea` for fetching by server actions, instead of going into long winded explanations and endless github tickets, explaining "why your stuff is not being cached".


@tomer-dev oh wow not sure what you mean by that, has anything new happened?

**Comment by markomitranic** [comment]
> The Next.js team [recommends using a data access layer](https://nextjs.org/blog/security-nextjs-server-components-actions#choosing-your-data-handling-model) for anything but quick prototyping. tRPC is that data layer for us.

@c-ehrlich can you please expand on this, I'd love to learn more. I don't see how TRPC is "a data layer for us". The main thing that a data layer does is API minimization, which trpc has nothing to do with - we have to write our own DTOs before shipping data to the client.

Some other activities associated with having a data layer:
- Authentication
- Input Validation & Sanitization
- Scope/Permission control
- API minimization (dtos and view/response transformation)

And none of these really have anything to do with our implementation of TRPC - the user has to write them themselves (yes, including input validation, which we use zod for).

Actually the only one out of all the data layer components, that we even remotely touch is that we **require** a zod definition as an input transformer, which again, nothing to do with trpc as a protocol, could be done with actions as well. So, our T3 trpc implementation basically just sets some general directions in terms of organizing our code elegantly, it does absolutely nothing to actually act as a data access layer.

So... what am I missing? Is there more functionality to our trpc implementation, that I don't know about yet :o

**Comment by tomer-dev** [comment]
Here's a trial to organize some thoughts:

In a video about server actions, Teo covered at least 4 different ways of
dealing with the fetch call (Client/server component/function in a data
layer/Form)
Then, tRPC is put in doubt - as discussed above. Nevertheless, not all
above methods infer a type.

As for Next, they costumized the fetch call. We love React Query though,
and we'll probably continue to use it with Server actions.

Now Server components come in React 19.

What will you use?

Will you utilize:
Next SC and tRPC, leaving SA for now?
Next SC, tRPC and one/more of the server actions methods bove?
Next SC, no tRPC because Server actions can generally cover the type
inference, and no RSC because we have everything in Next?

Next but gradually move to RSC? Ane no tRPC because Server actions?

What's Next, just React?

**Comment by tomer-dev** [comment]
Another confusion is performing an RPC in the same file with the client
logic.

React has made it so easy to make an RPC - It is easier than ever before to
skip the security aspect (sanitation, API min, etc..), unintentionally
over-sending information, or simply making an RPC in an unexpected manner,
in unexpected places.. raising the question of conciseness.

Enough to look at the controversy around styled components, which struggled
to find the balance between ease of use and the desire of fully
encapsulating a component in a single file. (Never seen a pure Styled
Component project, CSS is always very present)

Returning to SA, I like the good old Data Access layer approach.
I wonder what is the benefit of having RPC logic in the same file with
client code, seems like the server-client code is mixed enough at that
point.
