### ISSUE TITLE
feat: CLI allows to incrementally add T3 features

### ISSUE THREAD

**Issue by luismartinezs** [t3-oss/create-t3-app#1542]
### Is your feature request related to a problem? Please describe.

I have started a T3 project for a static site, with no tRPC.

Later I found out I want to call an API, and I want to use tRPC.

### Describe the solution you'd like to see

It would be nice if I could use the cli to add additional parts of the stack to a project already created.

E.g.

`npm create t3-app@latest` -> if we're in the root of a t3 project, it would be detected and the cli would say it detected a t3 project and would go through some steps to add additional parts of the stack

### Describe alternate solutions

Alternatively, add to the docs a section "how to add XXX to an already existing project"

**Comment by c-ehrlich** [comment]
This is borderline impossible because there is no way for the CLI to know what changes you have made to your project since scaffolding. Likewise, the docs would be a pain to maintain, and the versions in other languages would be guaranteed to be outdated after a short amount of time.

Here's a method for achieving this manually:
1. in one folder, create a t3 app that has the same packages as your current app
2. in another folder, create a t3 app that also has trpc
3. in the parent folder, `diff folder1 folder2`
