### ISSUE TITLE
feat: Feature branch deployments

### ISSUE THREAD

**Issue by peterHakio** [t3-oss/create-t3-app#1578]
### Is your feature request related to a problem? Please describe.

When building a production application it is pretty standard to deploy all feature branches or all branches with a pull request. Such that a link for testing can be created for testing purposes. Such that others can test the application before merging, without spinning the environment up locally.

### Describe the solution you'd like to see

A solution to this would be if somebody could create a github action that made a Vercel environment for each branch and a seperate action to pull it down down again. This github action could be added to the documentation and could be incorpareted into peoples projects. Ideally also working with auth0. Along with some guide if needed.

### Describe alternate solutions

If people would post their code in this issue or made a an example repo with feature branch deployments that was linked in this issue it would help the people that are looking for feature branch deployment methods and passes by this issue in the hunt for it.

**Comment by c-ehrlich** [comment]
This works the same way with CT3A as it would in any other Next.js app. See here: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

I don't think we should duplicate anything they do, but since we keep getting questions about this sort of stuff it might be worth communicating even clearer that we're "just" Next.js?
