### ISSUE TITLE
feat: use trpc.useContext() to invalidate query instead router.resfresh()

### ISSUE THREAD

**Issue by bibblebabl** [t3-oss/create-t3-app#1603]
### Is your feature request related to a problem? Please describe.

Right now in the example we are using Next Router to hardly refresh a page to see updated results in the database.

`src/app/_components/create-post.tsx`
```ts
  const createPost = api.post.create.useMutation({
    onSuccess: () => {
      router.refresh();
      setName("");
    },
  });
```

### Describe the solution you'd like to see

According to tRPC documentation we should be able to use something like this

`src/app/_components/create-post.tsx`
```ts
const utils = api.useContext();

  const createPost = api.post.create.useMutation({
    onSuccess: () => {
      utils.post.invalidate();
      setName("");
    },
  });

```

But right now it doesn't effect anything

### Describe alternate solutions

According to this documentation it should be the way how we should deal with invalidation of queries https://trpc.io/docs/client/react/useContext#query-invalidation

**Comment by c-ehrlich** [comment]
`invalidate` doesn't work because it's a server component, there is nothing in tRPC's context to invalidate client-side.

`route.refresh` doesn't perform a hard refresh, it just re-fetches data and rerenders server components, see https://nextjs.org/docs/app/api-reference/functions/use-router#userouter

**Comment by bibblebabl** [comment]
@c-ehrlich why it's a server component when create-post is marked with "use client" as a client-one?

**Comment by pingustar** [comment]
@c-ehrlich but doesnt this refresh all queries on the current page? 

And what if I have two concurrent mutations, it seems this usecase isnt supported by router.refresh?

And how do I show a loading screen for only the content that is being refreshed?

Is there a way to use the old style of client components and invalidation?

**Comment by c-ehrlich** [comment]
Client components work exactly as before. Server components are just an additional pattern that you can choose to use where it makes sense.

**Comment by pingustar** [comment]
> Client components work exactly as before. Server components are just an additional pattern that you can choose to use where it makes sense.

it seems that `const ctx = api.useContext();` is flagged as deprecated. What is the new pattern for client side component invalidation?

**Comment by c-ehrlich** [comment]
https://trpc.io/docs/client/react/useUtils

**Comment by bram209** [comment]
@c-ehrlich 

Would be nice if we can use https://nextjs.org/docs/app/api-reference/functions/unstable_cache
so that we can have a server-side equivalent of the revalidate utils, so that in the mutation we can do `utils.some.query.revalidate()` and it will translate to > `revalidateTag(...)`

Still annoying that you would have to revalidate client + server caches individually : (
Would be amazing if we have a unified way to clear _any_ cache for a specific query.
