### ISSUE TITLE
feat: Out of the box React Query ESLint plugin when using tRPC

### ISSUE THREAD

**Issue by ahkhanjani** [t3-oss/create-t3-app#1746]
### Is your feature request related to a problem? Please describe.

Not really a problem.

### Describe the solution you'd like to see

The [official ESLint plugin](https://tanstack.com/query/v4/docs/eslint/eslint-plugin-query) seems promising. I'm not sure why it isn't already included. If there is a reason I would like to know it.

### Describe alternate solutions

-

**Comment by FleetAdmiralJakob** [comment]
Sound promising, but does it work with tRPC?

**Comment by ahkhanjani** [comment]
> Sounds promising, but does it work with tRPC?

That's a good question. I tried to make it error but I failed. I think a tRPC expert could answer this.

**Comment by juliusmarminge** [comment]
I dont see any value using it along with trpc.

- [exhaustive deps](https://tanstack.com/query/v4/docs/eslint/exhaustive-deps) - trpc sets keys for you so this rule is irrelevant
- [prefer-object-syntax](https://tanstack.com/query/v4/docs/eslint/prefer-query-object-syntax) - also irrelevant since there is only a single valid syntax when using trpc
- [stable-query-client](https://tanstack.com/query/v4/docs/eslint/stable-query-client) - the initialized code handles this
