### ISSUE TITLE
feat: PlanetScale w/ foreign key constraints

### ISSUE THREAD

**Issue by ahkhanjani** [t3-oss/create-t3-app#1788]
### Is your feature request related to a problem? Please describe.

Are you planning on adding support to it? I wanted to ask before creating a PR.

### Describe the solution you'd like to see

-

### Describe alternate solutions

-

**Comment by c-ehrlich** [comment]
What would it mean for Create T3 App to add support for PlanetScale FK?

As far as I can tell, the requirements are
- enable FK support for your database in the PlanetScale dashboard
- start using FKs instead of for example [Drizzle's `relations`](https://planetscale.com/blog/working-with-related-data-using-drizzle-and-planetscale)

If the suggested method for "supporting" them is to add an option to the CLI, I am against it
1. There is no way for us to make it work out of the box - users have to enable FK for their DB first
2. PlanetScale documentation mostly suggests not to use them [(1)](https://planetscale.com/docs/concepts/foreign-key-constraints) [(2)](https://planetscale.com/docs/learn/operating-without-foreign-key-constraints#why-does-planetscale-not-recommend-constraints-) and instead rely on other methods of [ensuring referential integrity](https://planetscale.com/docs/learn/strategies-for-maintaining-referential-integrity)

But leaving this open for discussion
