### ISSUE TITLE
bug: Error: Tried to access "$types.prototype" which is not available at runtime

### ISSUE THREAD

**Issue by muhaimincs** [t3-oss/create-t3-app#1813]
### Provide environment information

`ct3aMetadata.initVersion: 7.30.0`

```bash
npx envinfo --system --binaries

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 1.14 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
    pnpm: 8.12.0 - /usr/local/bin/pnpm
    bun: 1.0.8 - ~/.bun/bin/bun
```

### Describe the bug

<img width="886" alt="image" src="https://github.com/t3-oss/create-t3-app/assets/30996641/91ec621e-1429-49cd-ba14-a095b4249d52">

### Reproduction repo

none

### To reproduce

just run
```
pnpm create t3-app@latest
cd <DIR>
pnpm dev
```

**Comment by zohaibakber** [comment]
yep same issue this happens after latest trpc version@11.0.0-rc.329

**Comment by juliusmarminge** [comment]
Just initted one to test and can't reproduce:

![CleanShot 2024-04-01 at 17 52 09@2x](https://github.com/t3-oss/create-t3-app/assets/51714798/560022d5-7681-4d47-bfe3-cd618d779b35)

---

Since you didn't provide a reproduction repo, and didn't say what package combo you're using I will close. Feel free to open a new issue with a proper reproduciton repo
