### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by maybebansky** [t3-oss/create-t3-app#1815]
### Provide environment information

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 985.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.0 - ~/.nvm/versions/node/v21.6.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.0/bin/npm
    pnpm: 8.14.2 - /opt/homebrew/bin/pnpm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman

### Describe the bug

Im trying to set up a project but there seems to be a typescript error:
```
src/server/db.ts:13:5 - error TS2322: Type 'PrismaPlanetScale' is not assignable to type 'never'.

13     adapter: new PrismaPlanetScale(psClient),
       ~~~~~~~


Found 1 error in src/server/db.ts:13
```

Im using:
- page router
- prisma
- no auth

### Reproduction repo

na

### To reproduce

Create a new project with Prisma, page router and no auth.

**Comment by dmarticus** [comment]
I ran into the same issue (I probably did the same thing you did), and after poking around a bit I think I may know what the problem is.

The PlanetScale Prisma adapter is an preview feature, and needs to be enabled thusly in the `schema.prisma` file.  This is by default in the repo when you initially create it (when you run `npx create-t3-app@latest`, you get a `schema.prisma` file that looks like this)

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["driverAdapters"] // this line is what enables the prisma adapters, see https://github.com/prisma/prisma/discussions/21347
}

datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
    // If you have enabled foreign key constraints for your database, remove this line.
    relationMode = "prisma"
}

model Post {
    id        Int      @id @default(autoincrement())
    name      String
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    @@index([name])
}
```

But, when you go to set up a planetscale DB in the planetscale app, they give you a `schema.prisma` file to copy into your repo when you initialize your DB, and the schema.prisma file they give you looks like this:

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider = "prisma-client-js"
  
}

model Post {
  id        Int      @id @default(autoincrement())
  name      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@index([name])
}
```

If the PlanetScale driver adapter isn't enabled, then `npm i` for those adapter features will fail.

So, the problem here is that the planetscale docs don't include the planetscale driver features by default, and my guess is you copied them over and the install failed (I did the same thing initially!)

If you include the 

```
  previewFeatures = ["driverAdapters"]
```

in the `schema.prisma` file, the install should work great.  Hope this helps!
