### ISSUE TITLE
feat: Bug or feature? Server-side calls are not being cached

### ISSUE THREAD

**Issue by Sid-Turner-Ellis** [t3-oss/create-t3-app#1833]
### Is your feature request related to a problem? Please describe.

Not sure if this is a bug or a missing feature, but one of the key patterns with the app router is to call fetch in multiple components and have those requests cached on a per-request level (https://nextjs.org/docs/app/building-your-application/data-fetching/patterns#fetching-data-where-its-needed).

Right now, calling the same query in multiple RSC will cause multiple requests.

### Describe the solution you'd like to see

Ideally, all procedures would make use of reacts Cache function

### Describe alternate solutions

Right now, i'm having to wrap the rTRPC calls in react's Cache function:

`api.post.hello = cache(() => api.post.hello())`

**Comment by yairopro** [comment]
> Right now, i'm having to wrap the rTRPC calls in react's Cache function:
`api.post.hello = cache(() => api.post.hello())`

A solution to make every trpc procedure wrapped with the react's cache would be to map its leaves with some utility like:
```typescript
import {cache} from "react"
// ...
export const trpc = mapLeaves(router, cache);
```
The `mapLeaves` would recursively map every leaf (the procedures) of the structure (the router).

**Comment by juliusmarminge** [comment]
You can open this as a feature request in trpc

**Comment by yairopro** [comment]
Hi @juliusmarminge 
Sorry, but I think you miss the point. 
The cache we are talking about **is per react-rendering**. Which means that for each server-side rendering, the cache is not shared between them.
Setting a cache inside the TRPC level will share the cached data across multiple rendering (since rendering is outside the TRPC scope). And that will be a problem: what we try to render for a user might be completely different for another one.

**Comment by Wundero** [comment]
@yairopro I think @juliusmarminge is mainly saying this is out of scope of the planned work for CT3A, and that if this is a feature you want support for, it makes more sense to ask in the trpc project instead.

**Comment by yairopro** [comment]
Hi @Wundero 

> this is out of scope of the planned work for CT3A

Ok. I don't want to bother.

>  it makes more sense to ask in the trpc project instead

No, it makes less sense (sorry @Wundero) because TRPC is not related to the "react rendering", or event react at all. While this cache feature is about caching TRPC calls for during an SSR. That's why I still think it should be at the link between NextJS and TRPC (this repo).

But anyway, if it's out of the planned work, I might just have to fork I guess.

**Comment by Wundero** [comment]
> No, it makes less sense (with all respect) because TRPC is not related to the "react rendering", nor even to react at all. While this cache feature is all about caching TRPC calls for during an SSR. That's why I still think it should be at the link between NextJS and TRPC (this repo).

TRPC is actually quite ingrained into the react/nextjs ecosystem. There has been much work done on their side to support the nextjs app router, among other nextjs-specific behaviors. A feature like this is well within their scope of work, and while they are certainly swamped as an OSS project, I think it is something users could benefit from if it is implemented correctly. Additionally, this repo is not the only repo which uses trpc and nextjs together, so it makes sense to me to implement this closer to tprc's side of things anyways.

I am not really sure the best route is to implement the feature on our side either, since it likely would best be served from the trpc server-side query client, rather than the router itself. For example:
```ts
const getQueryClient = cache(createQueryClient);
const caller = createCaller(createContext, {
  // Put something here
});
```
This way, procedures could be cached for a response in their entirety. Unfortunately, this isn't really supported externally, though you could probably patch trpc to add this yourself:

<details>

<summary>
Patch
</summary>

```patch
--- @trpc/server/src/unstable-core-do-not-import/router.ts
+++ @trpc/server/src/unstable-core-do-not-import/router.ts
@@ -15,3 +15,4 @@
import { isFunction, mergeWithoutOverrides, omitPrototype } from './utils';
+import { cache } from 'react';

export interface RouterRecord {
@@ -279,30 +279,30 @@
return createRecursiveProxy<ReturnType<RouterCaller<any, any>>>(
  async ({ path, args }) => {
    const fullPath = path.join('.');

    if (path.length === 1 && path[0] === '_def') {
      return _def;
    }

-   const procedure = _def.procedures[fullPath] as AnyProcedure;
+   const procedure = cache(_def.procedures[fullPath] as AnyProcedure);

    let ctx: Context | undefined = undefined;
    try {
      ctx = isFunction(ctxOrCallback)
        ? await Promise.resolve(ctxOrCallback())
        : ctxOrCallback;

      return await procedure({
        path: fullPath,
        getRawInput: async () => args[0],
        ctx,
        type: procedure._def.type,
      });
    } catch (cause) {
      options?.onError?.({
        ctx,
        error: getTRPCErrorFromUnknown(cause),
        input: args[0],
        path: fullPath,
        type: procedure._def.type,
      });
      throw cause;
    }
  },
);
```

</details>

**Comment by juliusmarminge** [comment]
`@trpc/react-query/rsc` is an entrypoint with helpers for server component integration with React Query. I think (and have made some initial attempts at implementing) it makes perfect sense to have this be part of that (hence why I asked you to open this there)

**Comment by Dastari** [comment]
Not sure if there was another solution for this however, I resolved this by using **node-cache**

```ts
import NodeCache from "node-cache";
import { api } from "@/trpc/server";
import { DataTable} from "@/components/data-table";

const cache = new NodeCache({ stdTTL: 300, checkperiod: 320 }); //

type Params = {
  page?: string;
  limit?: string;
  sort?: string;
  order?: "asc" | "desc";
};

export default async function Page(props: {
  searchParams: Promise<Params>;
}) {
  const params = await props.searchParams;

  const cacheKey = JSON.stringify(params);
  let tableProps = cache.get(cacheKey);

  if (!tableProps) {
    tableProps = await api.records.list(params);
    cache.set(cacheKey, tableProps);
  }

  return (
    <main className="flex h-screen flex-col overflow-hidden p-6">
        <DatatableTable {...tableProps} />
    </main>
  )
}
```

**Comment by dBianchii** [comment]
Curious to know if this has been solved?
