### ISSUE TITLE
FAQ for the common bs

### ISSUE THREAD

**Issue by TheoBr** [t3-oss/create-t3-app#210]
"why can't I run without a DB url?"
"what database can I use?"
"how do I add X to my next-auth session?"
"can I use vanilla JS?"

I think an FAQ is worth doing. Can work on it tomorrow if y'all agree

**Comment by nexxeln** [comment]
I agree.
I was also thinking that we should make the website a bit better, add the FAQ and the axioms there as well.

**Comment by bhatvikrant** [comment]
Is anyone working on this?

**Comment by riolly** [comment]
Here is my story using create-t3-app for the first time.
As junior dev.

Because I tried create-t3-app with next-auth, but never going through _next-auth getting started_ guide before and expect everything just work.
So I try to implement the google auth provider and it's not working and ended up spending hours debugging.
Then I finally just follow the next-auth getting started & guide, try next-auth in isolation, and after that I can fix it in just a second.

So it will be good to encourage people to try each of the individual components before using this.
So they can understand how everything is put together and can easily extend the configuration.

**Comment by TheoBr** [comment]
"Why are there JS files in the repo?"

**Comment by royanger** [comment]
I want to get a basic version of this going with the idea that its easy to add questions. Is the preference to have this as part of README or its own .md file?

**Comment by nexxeln** [comment]
We were going to make a page in the docs site for this. But yeah the README for the generated project is also good. What do you think @juliusmarminge?

**Comment by juliusmarminge** [comment]
> We were going to make a page in the docs site for this. But yeah the README for the generated project is also good. What do you think @juliusmarminge? 

I'd say link to a page on the upcoming docs. We could also have a `Awesome board` there to solve #231, like [tRPC](https://trpc.io/docs/awesome-trpc).

**Comment by juliusmarminge** [comment]
> "Why are there JS files in the repo?"

https://github.com/t3-oss/create-t3-app/blob/main/template/base/README.md#why-are-there-js-files-in-here
