### ISSUE TITLE
.gitignore being created as _gitignore

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#212]
**Describe the bug**
What scaffolding a new t3 app, the gitignore file gets created with the filename `_gitignore`. Is there a reason for this or is it just a bug?

**To Reproduce**

1. Create a t3 app
2. Look at the files

**Expected behavior**
The file should be named correctly

**Screenshots**
<img width="235" alt="image" src="https://user-images.githubusercontent.com/8353666/179544019-d58f5aff-f6e5-4772-92be-108b3a5ca082.png">

**Comment by HaukeSchnau** [comment]
If I understand correctly, this is only an issue during project creation and is automatically fixed aferward, right?

It seems like this is because the project is first copied from the `template/base` directory (which has a `_gitignore` file as to not mess with git) and the file is renamed to `.gitignore` only after `npm install`.

A simple solution would be to move the `fs.rename` call from [`src/helpers/initGit.ts`](https://github.com/t3-oss/create-t3-app/blob/59f8ad4f2104aa1f11508b55da75c333dce03625/src/helpers/initGit.ts#L36) to [`src/helpers/scaffoldProject.ts` right below the `fs.copy` call](https://github.com/t3-oss/create-t3-app/blob/59f8ad4f2104aa1f11508b55da75c333dce03625/src/helpers/scaffoldProject.ts#L59), if this is really an issue for some users.

**Comment by HaukeSchnau** [comment]
Yep, agreed. The file should never be called `_gitignore`, even if the user chooses not to initialize the repo right away.

Since this is a rather simple issue, I went ahead and created [a PR for this](https://github.com/t3-oss/create-t3-app/pull/215)

**Comment by juliusmarminge** [comment]
Either this or remove the file if no git repo is initialized but I think it should probably always be present.
