### ISSUE TITLE
Different environment variables (prod/dev/...)

### ISSUE THREAD

**Issue by zanzlender** [t3-oss/create-t3-app#232]
**Is your feature request related to a problem? Please describe.**
I saw the new changes for env variables and I was thinking... Maybe it's not a feature request per se, more like a question... How does everyone handle different environments? For example I usually have **.env.development** and **.env.production** which have the same variables but different values, and then another **.env** where I keep the db url for Prisma, because I didn't want to bother with figuring out how to import it in prisma.schema.

**Describe the solution you'd like**
Ideally, all works together... Idk someone enlighten me :')

**Describe alternatives you've considered**
Make and copy different .env.*environment* files.

**Comment by c-ehrlich** [comment]
I think the 'default' way to use create-t3-app is to use the .env file for development, and Vercel for staging/production, separate env files are not necessary for that workflow. Curious what others think?

**Comment by wlechowicz** [comment]
I only use .env.local which is for my local development (and is gitignored) since it's the responsibility of the real environment to provide its variables - so the dev, qa and prod stacks provide the environment for the app to run in.
For things like env-specific runtime data - API keys, IDs, API origins (staging vs production etc) - I use config/dev.json config/qa.json config/prod.json which get loaded by a config lib, since in some cases those are not just strings but whole objects that configure the app in some way.

**Comment by juliusmarminge** [comment]
I am not familiar with such a setup since I have never worked on a corporate codebase like this just yet. That said, I think this is beyond the scope of ct3a. We scaffold a very good starting point and I think many projects benefit from having type safe env-vars. If your stack does not allow for this setup or need something more complex, you should probably adapt this yourself and tailor it to your needs.

**Comment by nexxeln** [comment]
Closing this now
