### ISSUE TITLE
feat: i18n

### ISSUE THREAD

**Issue by SteveMelons** [t3-oss/create-t3-app#332]
### Is your feature request related to a problem? Please describe.

i18n - Internationalization (mainly but not only translations) is something most people from non English speaking countries need for their web app.

### Describe the solution you'd like to see

Fully integrate i18n into the t3 stack. Have i18n as a selectable option for setting up the project.

### Desribe alternate solutions

Structure the project in a way that implementing or opting into i18n is not as complex and have some kind of guide to getting things to work or the best way to set things up.

### Additional information

I kept my formulations in this feature request unopinionated but I think an opinionated solution for this problem would be very welcomed. For example the nextjs i18next framework/package (https://github.com/i18next/next-i18next).

**Comment by juliusmarminge** [comment]
Dont think this lays in create-t3-app's responsibility. Most apps are probably english only and if you need to support native languages that's on you.

**Comment by eddyhdzg** [comment]
How can I add next-i18next into this project?

**Comment by nexxeln** [comment]
> How can I add next-i18next into this project?

Just add it lol

**Comment by c-ehrlich** [comment]
I'm also against this.

> This is NOT an all-inclusive template and we expect you to bring your own libraries as well

The reason create-t3-app exists is because getting all of the pieces set up to work with each other on your own is quite difficult. Adding next-i18next is on a similar level as adding Zustand would be - you can follow their readme and have it up in a few minutes. Both are good libraries, but you can add them yourself.

**Comment by jmarianski** [comment]
I wouldn't consider adding i18n an easy task. It takes couple of hours++ to set it up properly so that it works well in next.js and in trpc server and isn't a hassle for future developers trying to develop in it.

I've created a setup that is working and I'm willing to share it:

https://github.com/jmarianski/t3-i18n

It is is sufficiently decoupled from the main source code (mostly config files, couple of demonstrations and - obviously - HOC attached in _app file) so that it should be possible to implement it in another couple of hours as a PR to this repository.

PS. Internationalization is a topic that affects a lot of developers that live in non-English countries that have to do the tedious task for every library to translate each error and nook and cranny that was left untranslated. Most of the modern web frameworks consider it and even create translations for their packages with the currently popular i18n implementation for the language. It would be a huge disservice to the community to leave this stack like that.

**Comment by riccardolardi** [comment]
@jmarianski I am getting a hydration error when using `withTranslation` HOC - I've reproduced the issue in a fresh T3 app here: https://github.com/riccardolardi/test-t3-i18n-withTranslation

Any clue if I'm dong something wrong or if that's an issue with the way i18n is integrated into T3?

**Comment by amannn** [comment]
Hello @juliusmarminge! 👋

I stumbled over this issue and wanted to chime in. I'm the maintainer of [🌐 `next-intl`](https://next-intl-docs.vercel.app/), a minimalistic solution for internationalization of Next.js apps.

I'm obviously biased, but I was wondering if you're still opposed to adding an i18n option to `create-t3-app`?

`next-intl` has a major focus on type safety and provides validation for messages. That's why I thought it might be a good fit for your CLI. Especially since all the libraries you present are optional, I think this could provide value for developers that need to support multiple languages without getting in the way of those that don't.

<img width="689" alt="Screenshot 2023-05-03 at 17 42 24" src="https://user-images.githubusercontent.com/4038316/235967611-ce097675-cd92-47c5-9144-0e5160b399c1.png">

In case you're interested, I could help to set this up. Also if you'd like to add an i18n section to your [other recommendations docs](https://create.t3.gg/en/other-recs), possibly also with library alternatives, I could help with that—just let me know!

**Comment by amannn** [comment]
@nickserv I totally agree, I personally use an i18n setup even if only a single language is supported precisely for the reasons you mention.

For a single-language setup, it's even easier to use `next-intl`: [App Router setup without i18n routing](https://next-intl.dev/docs/getting-started/app-router/without-i18n-routing). Since create-t3-app focuses on apps behind an auth layer, a setup with i18n routing is anyway the right call I'd say.

Here are a few highlights in regard to type safety:

### Type-safe messages

<img width="564" alt="Image" src="https://github.com/user-attachments/assets/57927565-35c7-4ad4-9c0d-bcce5a9f5023" />

### Type-safe formats

<img width="577" alt="Image" src="https://github.com/user-attachments/assets/81581a05-49ed-4530-a62e-fc81f0d8a55c" />

### Type-safe arguments

<img width="574" alt="Image" src="https://github.com/user-attachments/assets/7d733d99-2dfe-4a75-9c51-2c54856f43b8" />

(coming in [v4](https://next-intl.dev/blog/next-intl-4-0#strictly-typed-icu-arguments), currently in beta)

### Type-safe locales

<img width="566" alt="Image" src="https://github.com/user-attachments/assets/b9925b08-b3a7-459e-8e87-1de94cbcd39c" />

(coming in [v4](https://next-intl.dev/blog/next-intl-4-0#strictly-typed-icu-arguments), currently in beta)

### Type-safe routing

(relevant if you use [localized pathnames](https://next-intl.dev/docs/routing#pathnames))

```tsx
<Link
  href={{
    pathname: '/articles/[slug]',
    params: {
      // ✅ Slug provided
      slug: 'christmas-party'
    }
  }}
>
  Christmas party
</Link>

<Link
  href={{
    pathname: '/articles/[slug]',
    // ✖️ Missing params
  }}
>
  Christmas party
</Link>
```

Based on a [routing config](https://next-intl.dev/docs/routing):

```tsx
const routing = defineRouting({
  locales: ['en', 'de'],
  defaultLocale: 'en',
  pathnames: {
    '/': '/',
    '/articles/[slug]': {
      en: '/articles/[slug]',
      de: '/artikel/[slug]'
    }
  }
});
```

---

A good overview is the [TypeScript augmentation](https://v4.next-intl.dev/docs/workflows/typescript) page in the v4 beta docs.

Let me know if I can help with something or if you have questions!

**Comment by nickserv** [comment]
> For a single-language setup, it's even easier to use next-intl: [App Router setup without i18n routing](https://next-intl.dev/docs/getting-started/app-router/without-i18n-routing).

@amannn Oooh actually that's good to know for the Next app I'm working on, thank you! I think that's a good argument for CT3A as well, as you can still get i18n without the added complexity of i18n routing.

**Comment by nickserv** [comment]
No, I've just contributed to discussions and PRs. Note that you just have to check if a user's comment has a label on the right side (it seems to be member for most of the maintainers here).

**Comment by contrun** [comment]
@amannn Can you please kindly create some code to demonstrate how next-intl can work with create-t3-app? I myself, is also merely an user. It is obvious that users clearly desire to have i18n. Even if your PR will be not merged to upstream, it can serve as an example for how to integrate that with create-t3-app. This can be still be a huge favor to the community. I will very much appreciate this as a novice front end developer.

**Comment by amannn** [comment]
@contrun create-t3-app uses an approach where combinations of tools can result in different files, see e.g. https://github.com/t3-oss/create-t3-app/tree/main/cli/template/extras/src/app/layout

Therefore a PR might not be easiest way if you simply want to learn how to set up `next-intl`.

Instead, this guide here might help: [App Router setup without i18n routing](https://next-intl.dev/docs/getting-started/app-router/without-i18n-routing)
