### ISSUE TITLE
bug: .env is in .gitignore

### ISSUE THREAD

**Issue by ttsirkia** [t3-oss/create-t3-app#368]
### Provide environment information

Not relevant

### Describe the bug

In the template, `.env` is placed in `.gitignore` although docs state:

> Note: .env, .env.development, and .env.production files should be included in your repository as they define defaults.

https://nextjs.org/docs/basic-features/environment-variables

Is there a specific reason for the `.gitignore` decision in T3? Should it be just

```
# local env files
.env*.local
```

### To reproduce

Create new app and check `.gitignore`.

**Comment by TheoBr** [comment]
The next docs are bad practice. Don't commit your .env that's a terrible idea.

**Comment by meech-ward** [comment]
@TheoBr 


Personally I don't think env vars should ever be committed, but Next.js **and others** disagree:

* [Vite](https://vitejs.dev/guide/env-and-mode.html#env-files)
* [Create React App](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env)
* [Next](https://nextjs.org/docs/basic-features/environment-variables)
* [vue](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables)
* [Symfony](https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local)
* [Serverless framework](https://www.serverless.com/plugins/serverless-dotenv-plugin)

Wow, ok, I just started googling to see where the origin of `.env.local` came from. No idea, but i'm shoked by how many "things" suggest:

> The .env files should be committed to the repository because they are the same for all developers and machines. However, the env files ending in .local should not be committed because only you will use them.

This seems crazy to me, but shit, it's everywhere. I mean, [github's suggested `.gitignore`](https://github.com/github/gitignore/blob/main/Node.gitignore) still ignores `.env` so that's nice. But I'm still shocked.

So my original point was to say something like: maybe some people have gotten used to `.env` being committed and public, while `.env.local` is private. And maybe that's bad, but it's something.

So in the context of a Next.js app, it seems wrong to default to `.env` instead of `.env.local`, because of how `.env` is treated by default in Next.js. (and so many others)

I was 3 minutes into using `create-t3-app` trying to figure out why the `.env.local` file was missing. I legitimately thought it was this was just a next thing at the time. 

I get that it's ignored by git, but it feels wrong in the context of Next.js and could cause issues for anyone relying on Next's env var load order when running automated tests: https://nextjs.org/docs/basic-features/environment-variables#environment-variable-load-order

It kind of feels like playing too close to the edge. Devs that are used to how `.env.local` work might be upset that you've defaulted away from that. But maybe more importantly, some less experienced devs might uncomment `.env` and commit it, because next said to do it. Or they might start a new project without `create-t3-app` and commit a bunch of secrets into `.env` accidentally. 

---

Anyway, **a proposed solution:**

* Add a `.env.local` file to the template
* Put the default env vars in there
* keep an empty `.env` file and `.env` in the `.gitignore` if you like. Even add a comment saying the file is there because next is wrong but we'd rather play it safe so use `.env.local` 🤷‍♀️

**Prisma migrations:**

https://www.prisma.io/docs/guides/development-environment/environment-variables/using-multiple-env-files#migration-script

* install `dotenv-cli` as a dev dependency  
* Add this to the `package.json` scripts: `"migrate:dev": "npx dotenv -e .env.local -- prisma migrate dev"`
* use `yarn migrate:dev` instead of `npx prisma migrate dev`

**Comment by c-ehrlich** [comment]
We have documented this in both the template: https://github.com/t3-oss/create-t3-app/blob/cad79d18832d1fc904e0186f6920fdb1d7d749ea/cli/src/installers/envVars.ts#L49

And the docs: https://beta.create.t3.gg/en/usage/env-variables

> I get that it's ignored by git, but it feels wrong in the context of Next.js and could cause issues for anyone relying on Next's env var load order when running automated tests: https://nextjs.org/docs/basic-features/environment-variables#environment-variable-load-order

How so? Any variables added to `.env.test` will override `.env` in that environment. 

I think gitignoring `.env` is the right solution. I'd rather have people spend a few minutes confused where their .env.local file is, than to send their secrets to a public repo.

**Comment by meech-ward** [comment]
If I set `NODE_ENV` to `test`, then all env vars in `.env.local` are ignored. By using `.env`, you aren't providing a way to completely ignore env vars during automated testing. I don't really see this as an amazing feature or an issue, it's just some behaviour that exists that t3 app is taking away. 

> I think gitignoring .env is the right solution. I'd rather have people spend a few minutes confused where their .env.local file is, than to send their secrets to a public repo. People who prefer it the other way need to change one line in gitignore.

I agree with "I would rather people do x than to send their secrets to a public repo." But I'm afraid that it's currently backwards:

* `.env.local` is **never** committed and never public
* `.env` is often committed and public. By default is committed and made public

By using `.env.local` you're making it really difficult for someone to send their secrets to a public repo. They would have to be intentionally exposing secrets and being dumb. 

By using `.env`, you're making it much easier to send their secrets to a public repo.  The docs suggest you commit your `.env`, it's a common practice for many frameworks, and t3 is going **against** the grain.

**Comment by t3dotgg** [comment]
@meech-ward - Prisma CAN'T use env.local. We don't have another option.

Also more than happy to fight the norms in favor of best practice, that's the goal of this repo after all 🙏

**Comment by meech-ward** [comment]
T3 Open Source is great, you guys are great, I love and respect everything you're doing here. Please don't take any of my comments the wrong way, i'm just trying to have a friendly dialog and help out where I can. 

@t3dotgg 
> Prisma CAN'T use env.local. We don't have another option.

This is a lie and you know it and it makes me want to set the record straight even though it seems like a distraction from the main point of this issue. So real quick, for the record, Prisma **can** use `env.local`, it's just not elegant. 

```
npx dotenv -e .env.local -- prisma migrate dev
```

I share my thoughts on this in a video https://youtu.be/8DiT-LdYXC0?t=215 from 3:35-6:37

@t3dotgg 
> Also more than happy to fight the norms in favor of best practice, that's the goal of this repo after all 🙏

This is actually a pretty decent argument for an opinionated project. I really just wanted to see the env vars being used in the "normal" next way, or a note somewhere about why T3 is doing things differently. When I started using `create-t3-app`, I thought the missing `.env.local` file was a mistake and so I wanted to make sure I wasn't missing something. 

Can we add a note to the README.md about why you're using `.env` and tell people to never commit `.env` in their projects.

```
## T3 Axioms
...
4. Environment Variables

Some frameworks and build tools, like Next.js, suggest that you commit `.env` files to your project and only store secrets in `.env.local` files. This is a bad idea. Never commit `.env` files to your project. Never! In a T3 project, all `.env` files are ignored by git and you should use `.env` to store your environment variables, **not** `.env.local`. This means a T3 app will work seamsly with Pisma instead of having to write `npx dotenv -e .env.local -- ` in front of every Prisma command. 
```

Maybe even a comment in the `.gitignore` file too:

```
# environment variables
# Do not commit .env files, leave these alone!
.env
.env.production
!.env.example
``` 

I can't suggest changes without actually making a PR: https://github.com/t3-oss/create-t3-app/pull/869

Again, T3 Open Source is great, you guys are great, I love and respect everything you're doing here.

**Comment by t3dotgg** [comment]
The prisma example here is atrocious. Prisma indeed can't read from .env.local, you proved me right there.

Prisma, like all node apps, can have env variables overridden with a custom start script. Acting like that is an acceptable compromise for `npx prisma migrate` being broken is laughable.

I'm sorry man, we aren't gonna change this.

**Comment by meech-ward** [comment]
@t3dotgg I wanted a discussion where the intent of all this was crystal clear, and you've given that to me, so thank you 🙏 

I'm not trying to make you change your Prisma commands. But again, for the record, Prisma has this *unacceptable* compromise straight in their docs https://www.prisma.io/docs/guides/development-environment/environment-variables/managing-env-files-and-setting-variables#using-dotenv-cli-via-command-line

So if someone reads all the next docs, and all the Prisma docs, you can't really blame them for being curious about the `.env` decision in a t3 app
