### ISSUE TITLE
bug: git repo is kept when selecting `overwrite`

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#378]
### Provide environment information

```
  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 136.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Describe the bug

Since introducing overwrite option in #375 it seems like it's not overwriting the git repo. This is how it looks after I have created an app and committed an "external" file:

![CleanShot 2022-08-30 at 13 46 25@2x](https://user-images.githubusercontent.com/51714798/187428700-bdcf93f8-2471-41af-9e13-8bb13266e932.png)

Scaffolding a new app and selecting overwrite, doesn't overwrite the git repo, since this file is still committed afterwards.

### To reproduce

```bash
npx create-t3-app@beta
```
No need for any packages, just make sure to initialize Git.

Create a sample file, and commit it.

Now create another app in the same directory, once again, initialize Git.

You'll see the sample file is still committed, indicating the Git repo was not reset.

### Additional information

cc @c-ehrlich 

This should probably be validated at the step where the Git repo is initialized, something like:

```
The directory already includes a Git repo, would you like to delete it and create a new one?
```

can be prompted if selecting `Yes`?

> **NOTE:** I noticed the `.env` also isn't overwritten (probably goes for everything hidden (i.e. `.filename`).

**Comment by c-ehrlich** [comment]
I can reproduce this for `.git`, but not for other hidden files (`.env-example`, `.eslintrc.json`, `.gitignore`) on macOS 12.5.1.

Reference:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/8353666/187529227-5c0634f6-45d9-4898-9a6e-b399760c9f59.png">
(hope this screenshot is easy to parse - i put some junk into `.env-example`, created a new app with Overwrite, and the file was back to normal)

Maybe the difference is that `.git` is a hidden directory rather than a hidden file?

If I'm right that it's only about hidden directories, I agree with you about putting the check that you described in your post. If it can also apply to other hidden files (maybe depending on OS?), then we might have to think about a different solution. I don't like making special rules for anything other than `.git` - we'll add more hidden stuff at some point and forget to update the CLI.

**Comment by juliusmarminge** [comment]
Yea just the .git would be perfectly fine I think.
