### ISSUE TITLE
bug: Error: No QueryClient set, use QueryClientProvider to set one when trying to use ReactQueryDevTools

### ISSUE THREAD

**Issue by GregorGabric** [t3-oss/create-t3-app#379]
### Provide environment information

System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 8.69 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.08.15.00 - /usr/local/bin/watchman

### Describe the bug

I've included the devtools like so:

`  <SessionProvider session={session}>
      <ReactQueryDevtools initialIsOpen={false} context={session} />
      <Component {...pageProps} />
    </SessionProvider>`
insidte the _app.tsx file
and im getting this error 
Error: No QueryClient set, use QueryClientProvider to set

### To reproduce

`  <SessionProvider session={session}>
      <ReactQueryDevtools initialIsOpen={false} context={session} />
      <Component {...pageProps} />
    </SessionProvider>`

**Comment by c-ehrlich** [comment]
I can't reproduce this.

`create-t3-app@latest`
<img width="2556" alt="image" src="https://user-images.githubusercontent.com/8353666/187531740-43227232-4a3f-4087-93f3-5093d6cedcdd.png">

`create-t3-app@next`
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/8353666/187532469-cf615a35-a5a7-4935-86a2-c3599545c65e.png">

Could you make sure that the minimal reproduction as in my screenshots also breaks for you? Otherwise it's probably something else in your app.

**Comment by GregorGabric** [comment]
I was importing the new devtools 
`import { ReactQueryDevtools } from '@tanstack/react-query-devtools'`

downgraded to v3 and it works now. Thanks

**Comment by juliusmarminge** [comment]
My initial thought is that you are probably using a mismatched version of the dev tools, make sure that if you are on latest (v9 tRPC), use react-query-devtools, and if you are on next (v10 tRPC) use @tanstack/react-query-devtools
