### ISSUE TITLE
feat: Add createAt and updatedAt to the prisma models

### ISSUE THREAD

**Issue by mvandoff** [t3-oss/create-t3-app#618]
### Is your feature request related to a problem? Please describe.

Not really. But I wanted that attribute on the User and Account models for sure. I created one without it and had to delete it and remake it!

### Describe the solution you'd like to see

It's a minor improvement, but I think it would be useful to add createdAt and updatedAt attributes to at least one of the models in the default prisma.schema. It's something that I think most people want and wont know how to do at first. At least that was the case for me. 

### Desribe alternate solutions

Just add

```
model Example {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}
```

to Example

**Comment by c-ehrlich** [comment]
I also use `createdAt` and `updatedAt` fields in just about every project, and I'm leaning towards agreeing that this might be a good thing for us to include. I would expect most people to rip out the default models or at least expand on them, but it seems like a reasonable thing to have as a reference.

The question is: if we add it, which models should have it? Some possibilities are:

- Just the Example model - the smallest amount of additional code in order to include these fields in both model files.
- Just the User model - this way, non next-auth projects don't have it
- User, Session, Account models - same as above, just more code
- User and Example models 
- User, Session, Account, and Example models - the maximalist. This is how I set up my databases, but I think many people don't, and instead just include these fields on models where they feel like they will use them.

I'm leaning towards adding it to only the Example model. That way the User/Session/Account models remain identical to those in the Next-Auth documentation.

**Comment by nexxeln** [comment]
I think adding it in the Example model is a good idea. People can see how the `createdAt` and `updatedAt` work in prisma and we don't have to be different from the next-auth docs.
