### ISSUE TITLE
bug(docs): filtered folders still shows up in ToC

### ISSUE THREAD

**Issue by juliusmarminge** [t3-oss/create-t3-app#984]
We might want to hide elements from the TOC that's not actually displayed:

![CleanShot 2022-12-15 at 23 44 55](https://user-images.githubusercontent.com/51714798/207983196-ff38df17-7c3a-4bb8-8e30-4c6f81da981b.png)

_Originally posted by @juliusmarminge in https://github.com/t3-oss/create-t3-app/issues/963#issuecomment-1353811622_

**Comment by benmarg** [comment]
That's a great idea @juliusmarminge! I'll put together a PR for this one if you wanna assign me the ticket :)

**Comment by benmarg** [comment]
One other thing I noticed as I'm working on the fix for this: the last option in the Folder Structure is unreachable. If you have all 4 boxes checked and scroll to the bottom of the page, `tsconfig.json` never gets highlighted. If you de-select the Tailwind CSS filter, then `next.config.js` becomes the last highlighted option.

I'll try and fix this in my PR.

**Comment by juliusmarminge** [comment]
> One other thing I noticed as I'm working on the fix for this: the last option in the Folder Structure won't get highlighted, no matter how far your . If you have all 4 boxes checked and scroll to the bottom of the page, `tsconfig.json` never gets highlighted. If you de-select the Tailwind CSS filter, then `next.config.js` becomes the last highlighted option.
> 
> 
> 
> I'll try and fix this in my PR. 

If you mean highlighted in the TOC that depends on your monitor and resolution so don't put too much time into that one since it won't be the same for everyone no matter what we do

**Comment by benmarg** [comment]
That is what I meant! In that case we should be good to merge my PR!

**Comment by juliusmarminge** [comment]
#990 introduces this functionality although I think we can do better and refactor the current solution to be more "reusable" (See https://github.com/t3-oss/create-t3-app/pull/990#pullrequestreview-1222032120).

So still good to pick this up for anyone.

Also need to fix the mobile "On this page" to hide the elements as well

**Comment by darknet-00** [comment]
@juliusmarminge I want to ask about using the first approach that you mentioned in https://github.com/t3-oss/create-t3-app/pull/990#pullrequestreview-1222032120.

In the TOC there are general directory paths listed, like `src/server/trpc`, which are not present in the tree-configuration itself (all the files contained in that directory are listed though, for example `src/server/trpc/router/trpc.ts`). 

So my question is, is it a better approach to write logic to check if the string is contained in one of these paths, or add a new entry with the general directory path to the tree-configuration?

Writing the logic to find based on the string would be tedious in my opinion. If you have any tips, I would be happy to hear and try refactor the code.

**Comment by juliusmarminge** [comment]
If it's always a path should be pretty trivial to check if `"filename".startsWith(folderpath)`, or is there something I'm missing? Don't have a PC available to check the code out in a good way

**Comment by darknet-00** [comment]
Yes, but take for example `src/server`, it has multiple files in it of which every one of them belong to different groups (trpc, nextauth etc...). So you cannot really omit src/server from disappearing using this logic, because you cannot determine where this directory belongs (in this case it should be always visible).

I'm not sure If I expressed myself clear enough, but I tried writing some logic using this method, and it just isn't possible. Even if I somehow manage to make it work with the tree-structure as it is right now, it wouldn't be bulletproof and might break in the future.

Also, just to mention I'm not very proficient with Astro and maybe I'm missing something, so take my word with a grain of salt.

**Comment by juliusmarminge** [comment]
> Yes, but take for example `src/server`, it has multiple files in it of which every one of them belong to different groups (trpc, nextauth etc...). So you cannot really omit src/server from disappearing using this logic, because you cannot determine where this directory belongs (in this case it should be always visible).
> 
> I'm not sure If I expressed myself clear enough, but I tried writing some logic using this method, and it just isn't possible. Even if I somehow manage to make it work with the tree-structure as it is right now, it wouldn't be bulletproof and might break in the future.
> 
> Also, just to mention I'm not very proficient with Astro and maybe I'm missing something, so take my word with a grain of salt.

src/server seems to not work now either.

it should be hidden if none of the files inside it is shown.

maybe it isn't possible - seemed trivial at first glance but I might have underestimated it...

don't really have time for this before year's end. mind pushing your current solution and I can take a look?

**Comment by darknet-00** [comment]
Sure, no problem.
I have my changes somewhere stashed, I'll play around with it a bit more tomorrow and hopefully I can push it until the evening.

**Comment by benmarg** [comment]
Hey not sure where  we are at with this PR, I can go back and implement my original solution for the mobile "On this page" component if that's still needed! If we're going with an alternative solution then have we honed in on what that would look like yet? Since it seems like the above alternative solution turned out to be a bit harder to implement than we thought?

**Comment by darknet-00** [comment]
Just to update, I couldn't find a working solution for this matter. Maybe another approach would be better (perhaps the second one that Julius mentioned in the PR review), but I'm not capable of implementing that right now due to vague knowledge of how Astro works.

Since, I don't really have much time, I won't be able to work on this, so feel free to take it on.

**Comment by benmarg** [comment]
@juliusmarminge Thoughts on how to move forward with this issue? I haven't had a chance to look into the second approach you mentioned, do you still think it's feasible? Otherwise, I can just implement the functionality for the mobile component and we can close the issue.

**Comment by c-ehrlich** [comment]
This seems to have been fixed at some point
